openapi: 3.0.0
info:
  title: Demo-design-api
  version: '1.0'
  description: oro-demo-api
  contact:
    email: annguyen.dev0594@gmail.com
  license:
    name: MIT
servers:
  - url: 'http://localhost:3001'
    description: LOCAL_DEV
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              examples:
                example-1: {}
      operationId: get-users
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: userName
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'
      required:
        - id
    Post:
      title: Post
      type: object
      properties:
        id:
          type: string
          format: uri
        title:
          type: string
        author:
          type: string
      required:
        - id
  securitySchemes: {}
